### PR TITLE
Kotlin Version

### PR DESCRIPTION
**Pull request by vitorpamplona**
Kotlin's implementation of Negentropy.

### CODE REVIEW

**Comment by vitorpamplona** [comment]
This PR is now all set and running the tests perfectly.

**Comment by hoytech** [comment]
Thanks for this! I'm OK with merging this as-is, but most of the third-party implementations have so far preferred to keep their code in their own repos, and I will link to it in the Implementations section. It may be more convenient for you since I won't have to approve every future modification you make. Let me know what you'd prefer.

**Comment by vitorpamplona** [comment]
I can do either. Whatever is easy to keep testing all these versions for compliance. I can move it to my own repo and prepare a kotlin lib for others to use or copy this code over there. 

We might need to have a little script that downloads all versions and tests them all against each other.

**Comment by hoytech** [comment]
Cool, then let's keep the core Kotlin implementation in your repo to keep it consistent with the other implementations.

Good idea about making a single system for testing all the different implementations. Maybe we can make a parent repo that submodules in all the implementations.

**Comment by vitorpamplona** [comment]
Awesome! I will move this over and change this PR accordingly.

**Review by hoytech — APPROVED** [review]
Thank you!

**Pull request merged**
